### ISSUE TITLE
CMIC HACK - Rafa Navarro

### ISSUE THREAD

**Issue by rafaloz** [SciKit-Surgery/cmicHACKS2#17]
### 🚀 Feature
CMIC HACK - Rafa Navarro

### Motivation
CMIC HACKATHON 

### Pitch
Learning to train and deploy DL models for real-time segmentation of medical images.

**Comment by i-gayo** [comment]
[cju0tl3uz8blh0993wxvn7ly3.json](https://github.com/SciKit-Surgery/cmicHACKS2/files/13307500/cju0tl3uz8blh0993wxvn7ly3.json)
![cju0tl3uz8blh0993wxvn7ly3](https://github.com/SciKit-Surgery/cmicHACKS2/assets/37252647/c7d4fbf9-44e4-42d7-b9b8-e9fd0538a567)
