### ISSUE TITLE
Slides for learning outcomes of our Hackathon

### ISSUE THREAD

**Issue by mxochicale** [SciKit-Surgery/cmicHACKS2#36]
### 🚀 Feature

Preparing slides for learning outcomes of our Hackathon.

**Comment by rafaloz** [comment]
Hey,

are you coming to HH90 for the presentation? we might have an early lunch 

Rafa

**Comment by mxochicale** [comment]
Hi Rafa, sorry for the late reply. I just saw your message! let's catch up in coming days, will reach out via email to find a good time :) 

BTW I am also closing this issue with our successfully presentation https://scikit-surgery.github.io/cmicHACKS2/work-achieved  

Feel free to open this one if you have further feedback! 
Thanks, Miguel
